const questions = [
  {
    id: 1,
    question: "What is the capital of France?",
    correctAnswer: "Paris",
    possibleAnswers: ["Paris", "London", "Rome", "Berlin"],
    marks: 5,
  },
  {
    id: 2,
    question: "Which planet is known as the Red Planet?",
    correctAnswer: "Mars",
    possibleAnswers: ["Venus", "Mars", "Jupiter", "Saturn"],
    marks: 4,
  },
  {
    id: 3,
    question: "Who wrote 'Romeo and Juliet'?",
    correctAnswer: "William Shakespeare",
    possibleAnswers: [
      "Charles Dickens",
      "William Shakespeare",
      "Mark Twain",
      "Jane Austen",
    ],
    marks: 6,
  },
  {
    id: 4,
    question: "What is the largest ocean on Earth?",
    correctAnswer: "Pacific Ocean",
    possibleAnswers: [
      "Indian Ocean",
      "Pacific Ocean",
      "Atlantic Ocean",
      "Arctic Ocean",
    ],
    marks: 5,
  },
  {
    id: 5,
    question: "What is the chemical symbol for gold?",
    correctAnswer: "Au",
    possibleAnswers: ["Ag", "Au", "Pb", "Fe"],
    marks: 3,
  },
  {
    id: 6,
    question: "Which country hosted the 2020 Summer Olympics?",
    correctAnswer: "Japan",
    possibleAnswers: ["China", "Brazil", "Japan", "UK"],
    marks: 7,
  },
  {
    id: 7,
    question: "What is the tallest mountain in the world?",
    correctAnswer: "Mount Everest",
    possibleAnswers: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"],
    marks: 8,
  },
  {
    id: 8,
    question: "Who painted the Mona Lisa?",
    correctAnswer: "Leonardo da Vinci",
    possibleAnswers: [
      "Michelangelo",
      "Leonardo da Vinci",
      "Raphael",
      "Van Gogh",
    ],
    marks: 6,
  },
  {
    id: 9,
    question: "What is the smallest prime number?",
    correctAnswer: "2",
    possibleAnswers: ["0", "1", "2", "3"],
    marks: 2,
  },
  {
    id: 10,
    question: "Which gas do plants absorb from the atmosphere?",
    correctAnswer: "Carbon dioxide",
    possibleAnswers: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    marks: 4,
  },
  {
    id: 11,
    question: "What is the largest continent?",
    correctAnswer: "Asia",
    possibleAnswers: ["Africa", "Europe", "Asia", "North America"],
    marks: 5,
  },
  {
    id: 12,
    question: "Who discovered gravity?",
    correctAnswer: "Isaac Newton",
    possibleAnswers: [
      "Albert Einstein",
      "Galileo Galilei",
      "Isaac Newton",
      "Nikola Tesla",
    ],
    marks: 6,
  },
  {
    id: 13,
    question: "What is the currency of the United Kingdom?",
    correctAnswer: "Pound Sterling",
    possibleAnswers: ["Euro", "Dollar", "Pound Sterling", "Yen"],
    marks: 4,
  },
  {
    id: 14,
    question: "Which element has atomic number 1?",
    correctAnswer: "Hydrogen",
    possibleAnswers: ["Helium", "Oxygen", "Hydrogen", "Nitrogen"],
    marks: 3,
  },
  {
    id: 15,
    question: "In which year did World War II end?",
    correctAnswer: "1945",
    possibleAnswers: ["1939", "1942", "1945", "1950"],
    marks: 7,
  },
  {
    id: 16,
    question: "Which organ pumps blood in the human body?",
    correctAnswer: "Heart",
    possibleAnswers: ["Liver", "Brain", "Heart", "Lungs"],
    marks: 3,
  },
  {
    id: 17,
    question: "What is the fastest land animal?",
    correctAnswer: "Cheetah",
    possibleAnswers: ["Lion", "Horse", "Cheetah", "Tiger"],
    marks: 5,
  },
  {
    id: 18,
    question: "Which language is mainly spoken in Brazil?",
    correctAnswer: "Portuguese",
    possibleAnswers: ["Spanish", "French", "Portuguese", "English"],
    marks: 4,
  },
  {
    id: 19,
    question: "How many continents are there?",
    correctAnswer: "7",
    possibleAnswers: ["5", "6", "7", "8"],
    marks: 2,
  },
  {
    id: 20,
    question: "Who was the first person to walk on the Moon?",
    correctAnswer: "Neil Armstrong",
    possibleAnswers: [
      "Buzz Aldrin",
      "Yuri Gagarin",
      "Neil Armstrong",
      "Michael Collins",
    ],
    marks: 8,
  },
];

export default questions;
